language: node_js
node_js:
  - "0.12"
before_install: npm install -g grunt-cli
install:
  - npm install
script: grunt
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

